### ISSUE TITLE
TODO: change favicon to teknum's

### ISSUE THREAD

**Issue by aldy505** [elianiva/teknum-analytics#2]
[teknum-assets.zip](https://github.com/teknologi-umum/analytics/files/7690779/teknum-assets.zip)

^^ that is not a malware, I can guarantee that

**Comment by ghost** [comment]
https://virusscan.jotti.org/en-US/filescanjob/s6d4w847a1

Aprob

**Comment by elianiva** [comment]
#2

**Comment by elianiva** [comment]
hadeh salah lihat

**Comment by bryanwahyu** [comment]
wkwk kucing semua njir

**Comment by aldy505** [comment]
#5
